#!/bin/bash

 PERSON1=$1 #no space between before and after equal
 PERSON2=$2

echo "$PERSON1:: hi $PERSON2"
echo "$PERSON2:: hello $PERSON1"
echo "$PERSON1:: how are u"
echo "$PERSON2:: i am good,how are U"
