#!/bin/bash

SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14} # if user is not providing number of days, we are taking 14 days as default;

if [ $# -lt 2 ]
    then 
         USAGE # $ is not given infront of USAGE, because it is function
fi         

if [ ! -d "$SOURCE_DIR" ]
then
     echo -e "$SOURCE_DIR Does not exist ......please check"
     exit 1
fi

if [ ! -d "$DEST_DIR" ]
then
     echo -e " $DEST_DIR Does not exist ......please check"
     exit 1
fi
